# Generated by Django 4.1 on 2022-09-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='is_active',
            field=models.BooleanField(max_length=200),
        ),
    ]
