# Generated by Django 4.1 on 2022-09-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_speciality_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='code',
            field=models.IntegerField(),
        ),
    ]
