# Generated by Django 4.1 on 2022-09-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_speciality_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='dagree',
            new_name='degree',
        ),
    ]
