# Generated by Django 4.1 on 2022-09-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_dagree_teacher_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.CharField(choices=[('professor', 'Professor'), ('doctor', 'Rector')], max_length=10),
        ),
    ]
