# Generated by Django 4.1 on 2022-09-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_teacher_degree_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='specialities',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teachers',
        ),
        migrations.AddField(
            model_name='subject',
            name='specialities',
            field=models.ManyToManyField(to='courses.speciality'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(to='courses.teacher'),
        ),
    ]
